Feature/test
21ajayns/laravel-sanctum-api pull request #2
Opened 2022-02-18 12:50 UTC by 21ajayns

Testing for TaskController is completed with Request classes.

2022-02-20 22:06 UTC, boneymylady requested changes
A few minor changes.. Overall, :ok_hand:

2022-02-20 22:06 UTC, boneymylady commented on app/Http/Controllers/TaskController.php
> +    public function update(TaskCreateRequest $request, $id): Response
Is it `TaskUpdateRequest`?

2022-02-20 22:06 UTC, boneymylady commented on tests/Feature/Http/Controllers/TaskControllerTest.php
> +
Unwanted extra line

2022-02-20 22:20 UTC, boneymylady commented on app/Respositories/Interfaces/TaskRespositoryInterface.php
> +}
Missing line after closing parenthesis.

2022-02-21 05:47 UTC, 21ajayns reviewed
Changes Accepted

2022-02-22 03:19 UTC, boneymylady requested changes

2022-02-22 03:19 UTC, boneymylady commented on app/Repositories/Interfaces/ProductRepositoryInterface.php
> +use illuminate\support\Collection;
Capital `I` not `i` for `Illuminate`

2022-02-22 03:19 UTC, boneymylady commented on app/Repositories/Interfaces/TaskRepositoryInterface.php
> +use illuminate\support\Collection;
same here.

2022-02-22 03:35 UTC, boneymylady approved these changes

2022-02-22 03:39 UTC, merged