testing Comments for Tasks
21ajayns/laravel-sanctum-api pull request #3
Opened 2022-02-23 13:21 UTC by 21ajayns

Tasks should have Comments

2022-02-28 06:47 UTC, 21ajayns commented on tests/Feature/Http/Controllers/TaskControllerTest.php
> +        $response->assertJson([$comment->toArray()]);
should we assert comment separately?

2022-02-28 06:49 UTC, 21ajayns commented on tests/Feature/Http/Controllers/TaskControllerTest.php
> +        $this->assertDatabaseHas('comments', [
It says "title" not found in the comments table..!
is is because its a subset array on $expected?

2022-02-28 07:44 UTC, boneymylady requested changes

2022-02-28 07:44 UTC, boneymylady commented on tests/Feature/Http/Controllers/TaskControllerTest.php
> +        $response->assertJson([$comment->toArray()]);
```
$expected = [[
            'name' => 'task1',
            'description' => 'task-1',
            'status' => 'completed',
            'comments' => [
                $comment->toArray(),
            ],
        ]];

        $response = $this->json('GET', self::URI);
        $response->assertStatus(200);

        $response->assertJson($expected);
        ```

2022-02-28 07:44 UTC, boneymylady commented on tests/Feature/Http/Controllers/TaskControllerTest.php
> +            'body' => $expected['body']
Whether expected array has `title` and `body` key? Write down what is expecting here..
```
'title' => 'comment title',
'body' => 'comment body',
```

2022-03-02 04:56 UTC, boneymylady requested changes

2022-03-02 04:56 UTC, boneymylady commented on app/Http/Controllers/TaskController.php
> +    private CommentRepositoryInterface $commentRepository;
One line in between two repository declarations.

2022-03-02 04:56 UTC, boneymylady commented on app/Http/Controllers/TaskController.php
> +        if (\is_array($comment) === true && empty($comment) === false) {
Good.. :ok_hand:

2022-03-02 04:56 UTC, boneymylady commented on app/Models/Comment.php
> +    public function task()
Type hint the method - `public function task(): BelongsTo`

2022-03-02 04:56 UTC, boneymylady commented on app/Models/Comment.php
> +    public function toArray()
type hint here and all other methods.

2022-03-02 04:56 UTC, boneymylady commented on app/Repositories/CommentRepository.php
> +}
Leave a blank line at the end of the file.

2022-03-02 04:56 UTC, boneymylady commented on tests/Feature/Repositories/TaskRepositoryTest.php
> +        $repository2 = new CommentRepository;
`TaskRespositoryTest` should test only `TaskRepository` not `CommentRepository`. So test only one class/method at a time.

2022-03-02 04:56 UTC, boneymylady commented on tests/Feature/Repositories/TaskRepositoryTest.php
> +        //dd($result)
never leave commented code in PR. Please remove.

2022-03-02 04:56 UTC, boneymylady commented on tests/Feature/Repositories/TaskRepositoryTest.php
> +        $task->save();
Write one more task. Index should get a collection of tasks. So our test should cover more than one task as well.

2022-03-02 04:56 UTC, boneymylady commented on tests/Feature/Repositories/TaskRepositoryTest.php
> +            'status' => $result->getAttribute('status')
write down the expected array to make sure the data is actually updated.
```
$expected = [
            'name' => 'task1',
            'description' => 'task one',
            'status' => 'ongoing'
];
```

2022-03-02 04:56 UTC, boneymylady commented on tests/Feature/Repositories/TaskRepositoryTest.php
> +        $repository = new TaskRepository;
`$repository = new TaskRepository();`

2022-03-02 04:56 UTC, boneymylady commented on tests/Feature/Repositories/TaskRepositoryTest.php
> +        //dd($task);
Remove the commented from PR.

2022-03-02 04:56 UTC, boneymylady commented on tests/Feature/Repositories/TaskRepositoryTest.php
> +        $this->assertDatabaseMissing('tasks', [$task->getAttribute('id')]);
You should mention the missing param.
```
$this->assertDatabaseMissing('tasks', [
    'id' => $task->getAttribute('id')]
);
```

2022-03-02 04:56 UTC, boneymylady commented on tests/Feature/Repositories/TaskRepositoryTest.php
> +
remove blank line.

2022-03-03 03:10 UTC, boneymylady commented on tests/Feature/Repositories/TaskRepositoryTest.php
> +        $repository2 = new CommentRepository;
```
$taskRespository
```

2022-03-03 17:38 UTC, jomolmp approved these changes
All Good!!!

2022-03-07 01:50 UTC, boneymylady approved these changes

2022-03-07 01:50 UTC, boneymylady commented on tests/Feature/Http/Controllers/TaskControllerTest.php
>  use phpDocumentor\Reflection\Types\Void_;
Un used import?

2022-03-07 06:51 UTC, merged