checking api header
21ajayns/laravel-sanctum-api pull request #4
Opened 2022-03-04 09:45 UTC by 21ajayns

2022-03-04 10:35 UTC, jomolmp approved these changes
All good. Approved!

2022-03-07 02:25 UTC, boneymylady requested changes
Good attempt. A few changes.

2022-03-07 02:25 UTC, boneymylady commented on app/Exceptions/ApiSecretException.php
> +class ApiSecretException extends Exception
Be more specific with naming - `MissingApiSecretException` or `ApiSecretNotFoundException`.

2022-03-07 02:25 UTC, boneymylady commented on app/Http/Controllers/ApiHeaderController.php
> +        $Value = $request->header();
`$Value` or `$value`?

2022-03-07 02:25 UTC, boneymylady commented on config/apisecret.php
> +    'api-secret' => 'check-api-secret'
Underscores (for keys) are usually followed as standard practice

2022-03-07 02:25 UTC, boneymylady commented on app/Http/Middleware/ApiHeaderCheckMiddleware.php
> +        }
There is no problem in using `if` `else`. However, it is usually discouraged in the modern coding world due to hard to read. So you can short this code as 

```
if ($request->hasHeader('api-secret') && $request->header('api-secret') === $value) {
  return $next($request);
}
  throw new new ApiSecretException("Missing header credentials.");
```

2022-03-07 02:25 UTC, boneymylady commented on tests/Feature/Http/Controllers/ApiHeaderControllerTest.php
> +    }
You have to write 3 more tests and make sure that exception is thrown (`$this->expectException()`):
1. `$value = ['api-secret' => null]`
2. `$value = ['api-secret' => '']`
3. `$value = []`

2022-03-07 05:18 UTC, 21ajayns commented on tests/Feature/Http/Controllers/ApiHeaderControllerTest.php
> +        $this->withoutExceptionHandling();
This line was commented out!! Forgot to add

2022-03-07 05:50 UTC, boneymylady requested changes

2022-03-07 05:50 UTC, boneymylady commented on tests/Feature/Http/Controllers/ApiHeaderControllerTest.php
> +    }
As these three tests are doing the same assertion, you can provide the input via data provider. See the examples in repo.. More [examples](https://www.w3resource.com/php/PHPUnit/writing-tests-for-phpunit-data-providers.php) here.

2022-03-09 04:02 UTC, boneymylady approved these changes

2022-03-09 07:05 UTC, merged